name: CI

on:
  pull_request:
    branches: [main]

# # Update permissions block with additional permissions
# permissions:
#   pull-requests: write
#   deployments: write
#   statuses: write
#   contents: read
#   checks: write
#   actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Add token for authentication
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run typecheck || npm run build --if-present

      - name: Run lint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

  wait-for-vercel:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Wait for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: vercel-preview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60

      - name: Print Preview URL
        run: |
          echo "Preview URL: ${{ steps.vercel-preview.outputs.url }}"

      # Run Multion tests
      - name: Run Multion Tests
        id: multion-test
        env:
          MULTION_API_KEY: ${{ secrets.MULTION_API_KEY }}
        run: |
          OUTPUT=$(node multion-test.mjs "${{ github.event.pull_request.html_url }}" "${{ steps.vercel-preview.outputs.url }}")
          echo "preview_response<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Add comment to PR
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## Multion Test Results 🤖
            
            Preview URL: ${{ steps.vercel-preview.outputs.url }}
            
            PR Response: ${{ steps.multion-test.outputs.pr_response }}
            Preview Response: ${{ steps.multion-test.outputs.preview_response }}