name: CI

on:
  pull_request:
    branches: [main]

# Update permissions block to include contents read
permissions:
  pull-requests: write
  deployments: read
  statuses: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Add token for authentication
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run typecheck || npm run build --if-present

      - name: Run lint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

  wait-for-vercel:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: vercel-preview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 300

      - name: Print Preview URL
        run: |
          echo "Preview URL: ${{ steps.vercel-preview.outputs.url }}"
